services:
  jena:
    build:
      # https://github.com/apache/jena/tree/main/jena-fuseki2/jena-fuseki-docker
      context: https://github.com/apache/jena.git#main:jena-fuseki2/jena-fuseki-docker
      args:
        # https://hub.docker.com/_/alpine
        ALPINE_VERSION: 3
        # https://hub.docker.com/_/eclipse-temurin
        JAVA_VERSION: 26
        # start with 256MB, then go up until 2GB
        JAVA_OPTIONS: -Xms256m -Xmx2048m
        # https://repo1.maven.org/maven2/org/apache/jena/jena-fuseki-server/
        JENA_VERSION: 6.2.0
    command: --config /fuseki/config.ttl
    container_name: jena
    ports:
      - 3030:3030
    volumes:
      - ./config.ttl:/fuseki/config.ttl:ro,Z
      - ./data.ttl:/fuseki/data.ttl:ro,Z
  rdfproxy:
    build:
      context: ..
      dockerfile: ./Containerfile
    container_name: rdfproxy
    entrypoint: flask run --debug --port 8000 --host 0.0.0.0
    #entrypoint: gunicorn --bind 0.0.0.0:8000 --workers 8 --threads 8 --worker-class gevent --worker-tmp-dir=/dev/shm app:app
    environment:
      - FLASK_PREFIXES=templates/_prefixes.json
      - FLASK_SPARQL_ENDPOINT=http://jena.dns.podman:3030/example/sparql
    ports:
      - 8000:8000
    volumes:
      - ../app.py:/opt/rdfproxy/app.py:ro,Z
      - ../templates:/opt/rdfproxy/templates:ro,Z
