name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install Python
        run: uv python install
      - name: Install project dependencies
        run: uv sync
      - name: Run linter
        run: uv run pylint --output-format colorized --max-line-length 88 ./rdfproxy
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install Python
        run: uv python install
      - name: Install project dependencies
        run: uv sync --no-dev
      - name: Replace Podman SPARQL endpoint URL with Docker equivalent
        run: sed -i -e 's/jena.dns.podman/jena/g' example/compose.yml
      - name: Create containers
        run: docker compose --file example/compose.yml create
      - name: Start containers
        run: docker compose --file example/compose.yml start
      - name: Wait for application to be available
        run: curl --head --retry 30 --retry-all-errors --retry-delay 1 http://localhost:8000/
      - name: Test document conversion for HTML
        run: |
          curl --fail-with-body --output data.html --header "accept: text/html" http://localhost:8000/
          grep -q '<p>Example description here.</p>' data.html
      - name: Test document conversion for Turtle
        run: |
          curl --fail-with-body --output data.ttl --header "accept: text/turtle" http://localhost:8000/
          grep -q '<http://localhost:8000/> a schema:WebSite ;' data.ttl
      - name: Test document conversion for N3
        run: |
          curl --fail-with-body --output data.n3 --header "accept: text/n3" http://localhost:8000/
          grep -q '<http://localhost:8000/> a schema:WebSite ;' data.n3
      - name: Test document conversion for N-Triples
        run: |
          curl --fail-with-body --output data.nt --header "accept: application/n-triples" http://localhost:8000/
          grep -q '<http://localhost:8000/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/WebSite> .' data.nt
      - name: Test document conversion for JSON-LD
        run: |
          curl --fail-with-body --output data.jsonld --header "accept: application/ld+json" http://localhost:8000/
          grep -q '"@value": "Example description here."' data.jsonld
      - name: Test document conversion for RDF+XML
        run: |
          curl --fail-with-body --output data.rdf --header "accept: application/rdf+xml" http://localhost:8000/
          grep -q '<schema:WebSite rdf:about="http://localhost:8000/">' data.rdf
      - name: Test document conversion for HTML with type-specific template
        run: |
          curl --fail-with-body --output data.html --header "accept: text/html" http://localhost:8000/document
          grep -q '<p>Example document.</p>' data.html
      - name: Test document conversion for HTML with Markdown filter
        run: |
          curl --fail-with-body --output data.html --header "accept: text/html" http://localhost:8000/markdown
          grep -q '<del>This is struck through.</del>' data.html
      - name: Test document conversion for HTML with host-specific template
        run: |
          curl --fail-with-body --output data.html --header "accept: text/html" http://127.0.0.1:8000/test
          grep -q '<h1>Loopback</h1>' data.html
      - name: Test HTTP redirection for owl:sameAs
        run: |
          curl --head --fail-with-body --output data.txt http://localhost:8000/redirected
          grep -q 'Location: http://localhost:8000/document' data.txt
      - name: Test data publishing script
        run: |
          python cli.py --erase --data ../example/data --queries ../example/queries
        env:
          DEBUG: 1
          QUERY_ENDPOINT: http://localhost:3030/example/sparql
          UPDATE_ENDPOINT: http://localhost:3030/example/update
          GRAPH_IDENTIFIER: http://localhost:8000/
        working-directory: ./rdfproxy
      - name: Test document inserted by data publish
        run: |
          curl --fail-with-body --output data.ttl --header "accept: text/turtle" http://localhost:8000/published
          grep -q 'schema:description "Updated description for example document." ;' data.ttl
      - name: Stop containers
        if: always()
        run: docker compose --file example/compose.yml stop
