name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEFAULT_PYTHON_VERSION: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Use Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: pip
      - name: Update pip and setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install project dependencies
        run: python -m pip install -r requirements.txt
      - name: Install pylint
        run: python -m pip install pylint
      - name: Run linter
        run: python -m pylint --output-format colorized --max-line-length 88 ./rdfproxy
  test:
    name: Test
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Replace SPARQL endpoint URL for Docker use
        run: sed -i -e 's/jena.dns.podman/jena/g' example/compose.yml
      - name: Create containers
        run: docker compose --file example/compose.yml create
      - name: Start containers
        run: docker compose --file example/compose.yml start
      - name: Wait for application to be available
        run: curl --head --retry 30 --retry-all-errors --retry-delay 1 http://localhost:8000/
      - name: Test document conversion for HTML
        run: |
          curl --fail-with-body --output data.html --header "accept: text/html" http://localhost:8000/
          grep -q '<p>Example description here.</p>' data.html
      - name: Test document conversion for Turtle
        run: |
          curl --fail-with-body --output data.ttl --header "accept: text/turtle" http://localhost:8000/
          grep -q '<http://localhost:8000/> a schema:WebSite ;' data.ttl
      - name: Test document conversion for N3
        run: |
          curl --fail-with-body --output data.n3 --header "accept: text/n3" http://localhost:8000/
          grep -q '<http://localhost:8000/> a schema:WebSite ;' data.n3
      - name: Test document conversion for N-Triples
        run: |
          curl --fail-with-body --output data.nt --header "accept: application/n-triples" http://localhost:8000/
          grep -q '<http://localhost:8000/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/WebSite> .' data.nt
      - name: Test document conversion for JSON-LD
        run: |
          curl --fail-with-body --output data.jsonld --header "accept: application/ld+json" http://localhost:8000/
          grep -q '"@value": "Example description here."' data.jsonld
      - name: Test document conversion for RDF+XML
        run: |
          curl --fail-with-body --output data.rdf --header "accept: application/rdf+xml" http://localhost:8000/
          grep -q '<schema:WebSite rdf:about="http://localhost:8000/">' data.rdf
      - name: Test document conversion for HTML with type-specific template
        run: |
          curl --fail-with-body --output data.html --header "accept: text/html" http://localhost:8000/document
          grep -q '<p>Example document.</p>' data.html
      - name: Test HTTP redirection for owl:sameAs
        run: |
          curl --head --fail-with-body --output data.txt http://localhost:8000/redirected
          grep -q 'Location: http://localhost:8000/document' data.txt
      - name: Stop containers
        if: always()
        run: docker compose --file example/compose.yml stop
